telegram:
  token: '7910119865:AAE0sDHkSMR35W2wdEeZgNprK1eprSM4hOg'
  chat_id: '5459043780'

mutual_funds:
  BlackRock Global Funds - India Fund E2 (EUR):
    code: '0P0000VHLM'
    NAV:
      max: 50
      min: 40
    max_abs_variation: 3
  BlackRock Global Funds - Sustainable Energy Fund E2 (EUR):
    code: '0P0000VHMS'
  BlackRock Global Funds - World Gold Fund E2 (EUR):
    code: '0P0000VHO3'
  BlackRock Global Funds - World Healthscience Fund E2 (EUR):
    code: '0P0000VHO7'
  BlackRock Global Funds - World Technology Fund E2 (EUR):
    code: '0P0000VHOM'
  JPMorgan Funds - China Fund A (acc) - USD:
    code: 'F0GBR05VWX'
  JPMorgan Funds - Global Natural Resources Fund D (acc) - EUR:
    code: 'F0GBR064XS'
  Morgan Stanley Investment Funds - Global Brands Fund C (EUR):
    code: '0P0000MWCO'
  Pictet-Global Megatrend Selection R EUR:
    code: 'F0000026XE'
